aaran/Attendance/Database/Migrations/2024_03_14_081843_create_attendances_table.php
app/Livewire/Attendance/Attendance/Index.php
composer.lock
config/app.php
package-lock.json
resources/views/livewire/attendance/attendance/index.blade.php
resources/views/livewire/master/company/index.blade.php

#3 attendance work

---

Blog/Blogpost/Database/Factories/BlogpostFactory.php
Blog/Blogpost/Database/Migrations/2024_03_15_054911_create_blogposts_table.php
Blog/Blogpost/Database/Seeders/BlogpostSeeder.php
Blog/Blogpost/Model/Blogpost.php
Blog/Blogpost/Providers/BlogpostRouteServiceProvider.php
Blog/Blogpost/Providers/BlogpostServiceProvider.php
Blog/Blogpost/config.php
Blog/Blogpost/routes.php
app/Livewire/Blogpost/Index.php
app/Livewire/Blogpost/Upsert.php
app/Livewire/Webs/Home/BlogPost.php
bootstrap/providers.php
composer.json
composer.lock
package-lock.json
resources/views/components/menu/web-top.blade.php
resources/views/livewire/blogpost/index.blade.php
resources/views/livewire/blogpost/upsert.blade.php
resources/views/livewire/webs/home/blog-post.blade.php
routes/web.php

#4 Blogpost

---

app/Livewire/Entries/Sales/Upsert.php
app/Livewire/Taskmanager/Todos/Index.php

#19 Rework

---

app/Livewire/Entries/Purchase/Upsert.php
app/Livewire/Entries/Sales/Index.php
resources/views/livewire/entries/purchase/upsert.blade.php
resources/views/livewire/entries/sales/index.blade.php
resources/views/pdf/entries/sales/invoice.blade.php

#21 rework

---

aaran/Entries/routes.php
app/Http/Controllers/Entries/Purchase/InvoiceController.php
app/Livewire/Entries/Purchase/Index.php
app/Livewire/Entries/Purchase/Upsert.php
resources/views/livewire/entries/purchase/index.blade.php
resources/views/livewire/entries/purchase/upsert.blade.php
resources/views/pdf/entries/purchase/invoice.blade.php

#22 purchase invoice

---

resources/views/components/button/save.blade.php
resources/views/components/jet/authentication-card-logo.blade.php
resources/views/components/menu/web-top.blade.php
resources/views/livewire/utilities/icon/index.blade.php
resources/views/livewire/webs/home/index.blade.php

#30 reworking index

---

aaran/Audit/Database/Migrations/2024_01_07_190002_create_sales_bills_table.php
aaran/Audit/Database/Migrations/2024_03_07_190003_create_sales_bill_items_table.php
aaran/Audit/Models/Client/Sub/SalesTrackBill.php
aaran/Audit/Models/Client/Sub/SalesTrackBillItem.php
aaran/Audit/Models/Client/Sub/SalesTrackItem.php
aaran/Taskmanager/Database/Migrations/2023_11_10_202208_create_payment_slips_table.php
app/Livewire/Admin/Creditbook/Index.php
app/Livewire/Audit/Client/Index.php
app/Livewire/Audit/Client/Sub/SalesTrack/Bill.php
app/Livewire/Audit/Client/Sub/SalesTrack/BillItem.php
app/Livewire/Audit/Client/Sub/SalesTrack/Items.php
app/Livewire/Audit/Client/Sub/SalesTrack/TempBillItem.php
app/Livewire/Taskmanager/Task/Show.php
app/Models/User.php
resources/views/livewire/admin/creditbook/index.blade.php
resources/views/livewire/audit/client/index.blade.php
resources/views/livewire/audit/client/sub/sales-track/bill-item.blade.php
resources/views/livewire/audit/client/sub/sales-track/bill.blade.php
resources/views/livewire/audit/client/sub/sales-track/items.blade.php
resources/views/livewire/audit/client/sub/sales-track/temp-bill-item.blade.php
resources/views/livewire/taskmanager/activities/admin.blade.php
resources/views/livewire/taskmanager/gstcredit/index.blade.php
resources/views/livewire/taskmanager/payment-slip/index.blade.php
resources/views/livewire/taskmanager/task/show.blade.php

#34 aaran office copy

---

aaran/Taskmanager/Database/Migrations/2023_11_10_202208_create_payment_slips_table.php
resources/views/livewire/taskmanager/payment-slip/index.blade.php

#35 aaran office copy

---

resources/views/livewire/blog/post/index.blade.php

#37 rework on blog

---

app/Livewire/Master/Company/Upsert.php
resources/views/livewire/master/company/index.blade.php

#39 master company rework

---

aaran/Accounts/Database/Migrations/2022_10_07_000045_create_cashbooks_table.php
aaran/Accounts/Models/Cashbook.php
aaran/Accounts/Providers/AccountsRouteServiceProvider.php
aaran/Accounts/Providers/AccountsServiceProvider.php
aaran/Accounts/config.php
aaran/Accounts/routes.php
app/Livewire/Accounts/Cashbook/Create.php
app/Livewire/Accounts/Cashbook/Index.php
app/Livewire/Accounts/Cashbook/Update.php
app/Livewire/Controls/Model/Order/OrderModel.php
bootstrap/providers.php
resources/views/components/buttons/common-btn.blade.php
resources/views/components/buttons/save.blade.php
resources/views/components/menu/items/accounts-menu.blade.php
resources/views/components/menu/side-menu.blade.php
resources/views/components/menu/sub/accounts.blade.php
resources/views/livewire/accounts/cashbook/create.blade.php
resources/views/livewire/accounts/cashbook/index.blade.php
resources/views/livewire/accounts/cashbook/update.blade.php

#40 cash book

---

app/Livewire/Accounts/Cashbook/Index.php
resources/views/components/buttons/back.blade.php
resources/views/components/input/model-date.blade.php
resources/views/livewire/accounts/cashbook/index.blade.php

#44 cash book rework

---

app/Livewire/Accounts/Cashbook/Index.php
resources/views/livewire/accounts/cashbook/index.blade.php

#46 cash book rework

---

aaran/Master/Database/Migrations/2024_03_01_000201_create_companies_table.php
aaran/Master/Database/Seeders/CompanySeeder.php
aaran/Master/Models/Company.php
app/Listeners/SetTenantIdInSession.php
app/Livewire/Master/Company/Index.php
app/Livewire/Master/Company/Upsert.php
app/Livewire/Sys/DefaultCompany/Index.php
app/Models/DefaultCompany.php
app/Models/Tenant.php
app/Models/User.php
app/Scopes/TenantScope.php
database/factories/TenantFactory.php
database/migrations/0001_01_01_000000_create_users_table.php
database/migrations/0001_01_01_000008_create_tenants_table.php
database/seeders/DatabaseSeeder.php
resources/views/policy/navigation-menu.blade.php

#48 Working on tenant

---

database/seeders/DatabaseSeeder.php
database/seeders/DefaultCompanySeeder.php

#49 Working on tenant

---

app/Providers/EventServiceProvider.php
bootstrap/providers.php

#50 Working on tenant

---

app/Livewire/Entries/Sales/Index.php
resources/views/livewire/entries/sales/index.blade.php

#53 Working on sales filter

---

app/Livewire/Entries/Sales/Index.php
resources/views/livewire/entries/sales/index.blade.php

#55 Working on tenant

---

app/Livewire/Entries/Sales/Index.php
resources/views/livewire/entries/sales/index.blade.php

Working on date filter in sales

#56 Working on date filter in sales

---

aaran/Entries/Models/Payment.php
aaran/Entries/Models/Purchase.php
aaran/Entries/Models/Receipt.php
aaran/Entries/Models/Sale.php
aaran/Erp/Models/Production/Cutting.php
aaran/Erp/Models/Production/Ironing.php
aaran/Erp/Models/Production/Jobcard.php
aaran/Erp/Models/Production/PeInward.php
aaran/Erp/Models/Production/PeOutward.php
aaran/Erp/Models/Production/SectionInward.php
aaran/Erp/Models/Production/SectionOutward.php
aaran/Taskmanager/Models/Todos.php

#57 slno by company

---

aaran/Erp/Models/Production/Cutting.php
aaran/Erp/Models/Production/Ironing.php
aaran/Erp/Models/Production/PeInward.php
aaran/Erp/Models/Production/PeOutward.php
aaran/Erp/Models/Production/SectionInward.php
aaran/Erp/Models/Production/SectionOutward.php
aaran/Master/Database/Migrations/2024_03_01_000202_create_contacts_table.php
aaran/Master/Database/Seeders/ContactSeeder.php
aaran/Taskmanager/Database/Migrations/2024_03_01_000700_create_todos_table.php
app/Livewire/Master/Contact/Index.php
app/Livewire/Master/Contact/Upsert.php
app/Livewire/Taskmanager/Todos/Index.php

#58 rework

---

app/Livewire/Master/Company/Upsert.php
app/Livewire/Master/Contact/Upsert.php
app/Livewire/Taskmanager/Todos/Index.php
resources/views/livewire/master/company/upsert.blade.php

#59 rework on company

---

aaran/Audit/Database/Migrations/2023_09_22_030052_create_client_fees_table.php
aaran/Audit/Database/Migrations/2023_09_27_025000_create_client_banks_table.php
aaran/Audit/Database/Migrations/2023_09_27_034953_create_bank_balances_table.php
aaran/Audit/Database/Seeders/ClientSeeder.php
app/Livewire/Audit/Client/Balance.php
app/Livewire/Audit/Client/Bank.php
app/Livewire/Audit/Client/Fee.php
app/Livewire/Taskmanager/Activities/Admin.php
app/Livewire/Taskmanager/Activities/Index.php
app/Livewire/Taskmanager/PaymentSlip/Index.php
app/Livewire/Taskmanager/Task/AllTask.php
app/Livewire/Taskmanager/Task/Show.php
database/seeders/DatabaseSeeder.php
resources/views/components/menu/side-menu.blade.php
resources/views/livewire/taskmanager/payment-slip/index.blade.php
resources/views/livewire/taskmanager/task/all-task.blade.php
resources/views/livewire/taskmanager/task/mytask.blade.php

#62 rework on company

---

app/Livewire/Taskmanager/Todos/Index.php
resources/views/livewire/dashboard/index.blade.php

#66 todo rework

---

resources/views/pdf/entries/sales/invoice3.blade.php

#66  sales invoices

---

resources/views/livewire/offset/sales/upsert.blade.php

#69 rework

---

app/Livewire/Offset/Sales/Report.php
resources/views/auth/login.blade.php
resources/views/components/menu/web-top-new.blade.php
resources/views/livewire/offset/purchase/upsert.blade.php
resources/views/livewire/offset/sales/report.blade.php

#73 rework

---

app/Livewire/Offset/Sales/Report.php
app/Livewire/Sys/DefaultCompany/Index.php
resources/views/components/menu/top-menu.blade.php
resources/views/livewire/dashboard/index.blade.php
resources/views/livewire/sys/default-company/index.blade.php
resources/views/livewire/taskmanager/todos/index.blade.php

#75 rework

---

resources/css/app.css
resources/views/components/menu/web-top-new.blade.php
resources/views/components/menu/web-top.blade.php
resources/views/livewire/webs/home/about.blade.php
resources/views/livewire/webs/home/index.blade.php
resources/views/pdf/entries/purchase/invoice.blade.php
resources/views/pdf/entries/sales/invoice3.blade.php

#78  rework in home page

---

app/Listeners/SetSoftwareIdInSession.php
app/Models/Software.php
app/Models/User.php
app/Providers/EventServiceProvider.php
app/Scopes/SoftwareScope.php
database/factories/SoftwareFactory.php
database/migrations/0001_01_01_000000_create_users_table.php
database/migrations/2024_03_30_102120_create_software_table.php
database/seeders/DatabaseSeeder.php
resources/views/components/menu/side-menu.blade.php
resources/views/livewire/webs/home/index.blade.php

#80 software dividing

---

app/Livewire/Blog/Post/Index.php
composer.lock
package-lock.json
resources/views/livewire/blog/post/index.blade.php
resources/views/livewire/blog/post/upsert.blade.php
resources/views/livewire/blog/post/view.blade.php

blog post,rework on index file

#83 blog post,rework on index file

---

app/Livewire/Blog/Post/Index.php
app/Livewire/Blog/Post/Upsert.php
app/Livewire/Blog/Post/View.php
resources/views/components/input/rich-text.blade.php
resources/views/livewire/blog/post/index.blade.php
resources/views/livewire/blog/post/upsert.blade.php
resources/views/livewire/blog/post/view.blade.php

#88 rework on blog

---

resources/views/livewire/blog/post/upsert.blade.php

#89 rework on blog

---

app/Livewire/Blog/Post/Upsert.php
resources/views/livewire/blog/post/index.blade.php
resources/views/livewire/blog/post/upsert.blade.php

#96 rework on blog

---

app/Livewire/Blog/Post/View.php
resources/views/livewire/blog/post/view.blade.php

#115 working on like button

---

app/Livewire/Blog/Post/View.php
database/migrations/2024_03_16_193256_create_posts_table.php
resources/views/livewire/blog/post/view.blade.php

#118 reworking on comment box

---

app/Livewire/Blog/Post/Index.php
app/Livewire/Blog/Post/Upsert.php
app/Livewire/Blog/Post/View.php
app/Models/Blog/Comment.php
app/Models/Blog/Post.php
database/migrations/2024_03_16_193256_create_posts_table.php
resources/views/livewire/blog/post/index.blade.php
resources/views/livewire/blog/post/view.blade.php

#121 reworking on comment box

---

aaran/Blog/Database/Migrations/2024_03_16_193256_create_posts_table.php
aaran/Blog/routes.php
app/Livewire/Blog/Post/View.php
resources/views/livewire/blog/post/index.blade.php
resources/views/livewire/blog/post/view.blade.php

#133 rework comment box

---

aaran/Blog/Models/Comment.php
app/Livewire/Blog/Post/Upsert.php
app/Livewire/Blog/Post/View.php
resources/views/livewire/blog/post/upsert.blade.php
resources/views/livewire/blog/post/view.blade.php
resources/views/livewire/master/company/upsert.blade.php

#142 rework comment box

---

app/Livewire/Common/BankList.php
resources/views/livewire/common/bank-list.blade.php

#143 rework on bank

---

app/Livewire/Attendance/Attendance/Index.php
app/Livewire/Audit/BankStatementEntry/Index.php
app/Livewire/Audit/Client/Balance.php
app/Livewire/Audit/Client/Bank.php
app/Livewire/Audit/Client/BankDetails.php
app/Livewire/Audit/Client/Fee.php
app/Livewire/Audit/Client/Filling.php
app/Livewire/Audit/Client/Index.php
app/Livewire/Audit/Client/Show.php
app/Livewire/Audit/Gstcredit/Index.php
app/Livewire/Audit/PaymentSlip/Index.php
app/Livewire/Audit/Turnover/Index.php
app/Livewire/Blog/Post/Index.php
app/Livewire/Blog/Post/Upsert.php
app/Livewire/Blog/Post/View.php
resources/views/livewire/audit/client/bank.blade.php

#175 Rework on Bank

---

app/Livewire/Audit/Client/Filling.php
resources/views/livewire/audit/client/filling.blade.php
resources/views/livewire/audit/client/index.blade.php

#178 Rework on Gst Filling

---

resources/views/livewire/admin/creditbook/index.blade.php
resources/views/livewire/entries/purchase/index.blade.php
resources/views/livewire/entries/receipt/index.blade.php
resources/views/livewire/entries/sales/index.blade.php
resources/views/livewire/erp/production/cutting/index.blade.php
resources/views/livewire/erp/production/cutting/upsert.blade.php
resources/views/livewire/erp/production/ironing/index.blade.php
resources/views/livewire/erp/production/ironing/upsert.blade.php
resources/views/livewire/erp/production/jobcard/upsert.blade.php
resources/views/livewire/erp/production/pe-outward/upsert.blade.php
resources/views/livewire/erp/production/section-outward/upsert.blade.php
resources/views/livewire/master/company/index.blade.php
resources/views/livewire/master/contact/index.blade.php
resources/views/livewire/master/product/index.blade.php

#201 reworking on view files

---

resources/views/livewire/accounts/cashbook/index.blade.php

#207 reworking on cashbook

---

resources/views/livewire/entries/payment/index.blade.php
resources/views/livewire/entries/purchase/index.blade.php
resources/views/livewire/entries/receipt/index.blade.php
resources/views/livewire/entries/sales/index.blade.php

#223 Align entries table view

---

resources/views/components/button/new.blade.php
resources/views/livewire/entries/sales/index.blade.php

223 refactor in new button for responsive view

#223 refactor in new button for responsive view

---

app/Livewire/Developer/Installation/SoftwareDetails.php
resources/views/components/forms/top-controls-filter.blade.php
resources/views/components/input/toggle-filter.blade.php
resources/views/livewire/developer/installation/software-details.blade.php
resources/views/livewire/entries/sales/upsert.blade.php

235 rework on top_controls_blade and grand total alignment

#235 rework on top_controls_blade and grand total alignment

---

resources/views/components/button/back.blade.php
resources/views/components/button/save.blade.php
resources/views/components/table/delete.blade.php
resources/views/components/table/edit.blade.php
resources/views/livewire/accounts/cashbook/index.blade.php
resources/views/livewire/entries/payment/index.blade.php
resources/views/livewire/entries/purchase/index.blade.php
resources/views/livewire/entries/receipt/index.blade.php
resources/views/livewire/entries/sales/index.blade.php
resources/views/livewire/master/company/index.blade.php
resources/views/livewire/master/contact/index.blade.php
resources/views/livewire/master/product/index.blade.php
resources/views/livewire/reports/statement/receviables.blade.php

264 reworking on pops and  buttons

#264 reworking on pops and  buttons
