AARAN-SOFTWARE/aaran-soft

aaran/Common/Database/Factories/DepartmentFactory.php, aaran/Common/Database/Factories/LedgerFactory.php, aaran/Common/Database/Migrations/2024_02_26_081846_create_departments_table.php, aaran/Common/Database/Migrations/2024_02_26_082716_create_ledgers_table.php, aaran/Common/Database/Seeders/DepartmentSeeder.php, aaran/Common/Database/Seeders/LedgerSeeder.php, aaran/Common/Models/Department.php, aaran/Common/Models/Ledger.php, app/Livewire/Common/CountryList.php, app/Livewire/Common/DepartmentList.php, app/Livewire/Common/HsncodeList.php, app/Livewire/Common/LedgerList.php, app/Livewire/Common/PincodeList.php, config/app.php, database/seeders/DatabaseSeeder.php, resources/views/components/button/cancel.blade.php, resources/views/components/menu/items/common-menu.blade.php, resources/views/livewire/common/country-list.blade.php, resources/views/livewire/common/department-list.blade.php, resources/views/livewire/common/hsncode-list.blade.php, resources/views/livewire/common/ledger-list.blade.php, resources/views/livewire/common/pincode-list.blade.php, routes/web.php, tests/Feature/Livewire/Common/CountryListTest.php, tests/Feature/Livewire/Common/DepartmentListTest.php, tests/Feature/Livewire/Common/HsncodeListTest.php, tests/Feature/Livewire/Common/LedgerListTest.php, tests/Feature/Livewire/Common/PincodeListTest.php
work on country,pin-code,hsn-code,department,ledger
=> #8 work on country,pincode,hsncode,department,ledger

aaran/Master/Database/Factories/ProductFactory.php, aaran/Master/Database/Migrations/2024_02_26_104008_create_products_table.php, aaran/Master/Database/Seeders/ProductSeeder.php, aaran/Master/Models/Product.php, aaran/Master/routes.php, app/Livewire/Controls/Model/Common/HsncodeModel.php, app/Livewire/Master/Product/Index.php, app/Livewire/Master/Product/Upsert.php, resources/views/components/controls/lookup/model.blade.php, resources/views/livewire/controls/model/common/hsncode-model.blade.php, resources/views/livewire/master/product/index.blade.php, resources/views/livewire/master/product/upsert.blade.php, routes/web.php, tests/Feature/Livewire/Master/ProductListTest.php
=> #12 work on product

aaran/Common/Models/Pincode.php, aaran/Master/Database/Migrations/2024_02_26_111002_create_contacts_table.php, aaran/Master/Models/Contact.php, aaran/Master/routes.php, app/Livewire/Controls/Model/Common/CityModel.php, app/Livewire/Controls/Model/Common/PincodeModel.php, app/Livewire/Controls/Model/Common/StateModel.php, app/Livewire/Master/Contact/Index.php, app/Livewire/Master/Contact/Upsert.php, checknow, database/factories/ContactFactory.php, resources/views/livewire/controls/model/common/city-model.blade.php, resources/views/livewire/controls/model/common/pincode-model.blade.php, resources/views/livewire/controls/model/common/state-model.blade.php, resources/views/livewire/master/contact/index.blade.php, resources/views/livewire/master/contact/upsert.blade.php
=> #19 work on contact page

aaran/Master/routes.php, resources/views/components/forms/per-page.blade.php, resources/views/components/input/advance-search.blade.php
work on advanced-search and per-page
=> #14 work on advanced-search and per-page

app/Livewire/Controls/Model/Common/PincodeModel.php, app/Livewire/Controls/Model/Common/StateModel.php, resources/views/livewire/master/contact/index.blade.php, resources/views/livewire/master/contact/upsert.blade.php
=> #21 reworking on contact page

app/Livewire/Controls/Model/Common/HsncodeModel.php, app/Livewire/Master/Product/Upsert.php, resources/views/components/input/model-select.blade.php, resources/views/components/input/model-text.blade.php, resources/views/livewire/master/product/index.blade.php, resources/views/livewire/master/product/upsert.blade.php
=> #20 work on mobile view

app/Livewire/Controls/Model/Common/StateModel.php, app/Livewire/Master/Contact/Upsert.php, resources/views/livewire/controls/model/common/state-model.blade.php, resources/views/livewire/master/contact/index.blade.php, resources/views/livewire/master/product/upsert.blade.php
=> #24 rework on contact

app/Models/Master/Company.php, database/factories/Master/CompanyFactory.php, database/migrations/2024_02_29_062525_create_companies_table.php, database/seeders/CompanySeeder.php
=> #25 company table

package-lock.json, resources/css/app.css, resources/views/components/menu/web-top.blade.php, resources/views/livewire/webs/home/index.blade.php, tailwind.config.js, vite.config.js
working on index and about service
=> #25 working on index and about service

aaran/Entries/Database/Factories/SalesFactory.php, aaran/Entries/Database/Seeders/Sales.php, app/Livewire/Controls/Model/Common/LedgerModel.php, app/Livewire/Controls/Model/Common/TransportMode.php, app/Livewire/Controls/Model/Order/OrderModel.php, app/Livewire/Entries/Sales/Index.php, app/Livewire/Entries/Sales/Upsert.php, resources/views/components/menu/items/sales-menu.blade.php, resources/views/components/menu/sub/sales.blade.php, resources/views/livewire/controls/model/common/ledger-model.blade.php, resources/views/livewire/controls/model/common/transport-mode.blade.php, resources/views/livewire/controls/model/order/order-model.blade.php, resources/views/livewire/entries/sales/index.blade.php, resources/views/livewire/entries/sales/upsert.blade.php, tests/Feature/Livewire/Entries/Sales/IndexTest.php, tests/Feature/Livewire/Entries/Sales/UpsertTest.php
=> #32 sales livewire file

aaran/Entries/Database/Migrations/2024_03_02_000038_create_sales_table.php, app/Livewire/Controls/Model/Common/ColourModel.php, app/Livewire/Controls/Model/Common/SizeModel.php, app/Livewire/Controls/Model/Master/CompanyModel.php, app/Livewire/Controls/Model/Master/ContactModel.php, app/Livewire/Controls/Model/Master/ProductModel.php, app/Livewire/Entries/Sales/Index.php, app/Livewire/Entries/Sales/Upsert.php, resources/views/livewire/controls/model/common/colour-model.blade.php, resources/views/livewire/controls/model/common/size-model.blade.php, resources/views/livewire/controls/model/master/company-model.blade.php, resources/views/livewire/controls/model/master/contact-model.blade.php, resources/views/livewire/controls/model/master/product-model.blade.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #42 work on sales and sales-items

app/Livewire/Entries/Sales/Upsert.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #44 work on sales grand total

app/Livewire/Controls/Model/Master/ProductModel.php, app/Livewire/Entries/Sales/Upsert.php, database/seeders/DatabaseSeeder.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #47 sales rework

app/Livewire/Entries/Sales/Upsert.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #48 sales grand total  work

app/Livewire/Webs/Home/About.php, app/Livewire/Webs/Home/Contact.php, app/Livewire/Webs/Home/Service.php, package-lock.json, package.json, resources/css/app.css, resources/js/app.js, resources/views/components/menu/web-top.blade.php, resources/views/livewire/webs/home/about.blade.php, resources/views/livewire/webs/home/contact.blade.php, resources/views/livewire/webs/home/index.blade.php, resources/views/livewire/webs/home/service.blade.php, routes/web.php, tailwind.config.js
working on index and about service
=> #51 working on index and about service

resources/css/app.css, resources/js/app.js, resources/views/components/menu/web-top.blade.php, resources/views/livewire/webs/home/about.blade.php, resources/views/livewire/webs/home/contact.blade.php, resources/views/livewire/webs/home/index.blade.php, resources/views/livewire/webs/home/service.blade.php, tailwind.config.js
=> #51 working on index

resources/css/app.css, resources/js/app.js, resources/views/livewire/webs/home/about.blade.php, resources/views/livewire/webs/home/contact.blade.php, resources/views/livewire/webs/home/index.blade.php, resources/views/livewire/webs/home/service.blade.php
reworking on contact about and service
=> #61 reworking on contact about and service

app/Livewire/Entries/Sales/Upsert.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #62  sales calculation

app/Enums/GstPercent.php, app/Livewire/Common/CityList.php, app/Livewire/Entries/Sales/Upsert.php, app/Livewire/Trait/CommonTrait.php, resources/views/components/icons/spinner.blade.php, resources/views/livewire/common/city-list.blade.php, resources/views/livewire/common/size-list.blade.php
sales gst work and loading window page on city list
=> #65 sales gst work and loading window page on city list

app/Livewire/Entries/Sales/Upsert.php, resources/views/livewire/entries/sales/index.blade.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #68 sales rework

aaran/Entries/Models/Purchase.php, aaran/Entries/Models/Purchaseitem.php, app/Livewire/Entries/Purchase/Index.php, app/Livewire/Entries/Purchase/Upsert.php, app/Livewire/Entries/Sales/Index.php, app/Livewire/Entries/Sales/Upsert.php, resources/views/livewire/entries/purchase/index.blade.php, resources/views/livewire/entries/purchase/upsert.blade.php, resources/views/livewire/entries/sales/upsert.blade.php
=> #69 purchase

aaran/Common/Database/Seeders/TransportSeeder.php, aaran/Entries/Database/Seeders/SaleSeeder.php, composer.lock, database/seeders/DatabaseSeeder.php, package-lock.json
work on Transport & Sale Seeder
=> #63 work on Transport & Sale Seeder

aaran/Common/routes.php, aaran/Entries/Database/Migrations/2024_03_01_000503_create_receipts_table.php, aaran/Entries/Database/Migrations/2024_03_01_000504_create_payments_table.php, aaran/Entries/Models/Payment.php, aaran/Entries/Models/Receipt.php, aaran/Master/Database/Seeders/ProductSeeder.php, app/Livewire/Common/BankList.php, app/Livewire/Common/ReceipttypeList.php, app/Livewire/Controls/Model/Common/BankModel.php, app/Livewire/Controls/Model/Common/ReceipttypeModel.php, app/Livewire/Entries/Payment/Index.php, app/Livewire/Entries/Payment/Upsert.php, app/Livewire/Entries/Receipt/Index.php, app/Livewire/Entries/Receipt/Upsert.php, app/Livewire/Entries/Sales/Upsert.php, app/Livewire/Erp/Production/Ironing/Upsert.php, resources/views/components/menu/items/common-menu.blade.php, resources/views/livewire/common/bank-list.blade.php, resources/views/livewire/common/receipttype-list.blade.php, resources/views/livewire/controls/model/common/bank-model.blade.php, resources/views/livewire/controls/model/common/receipttype-model.blade.php, resources/views/livewire/entries/payment/index.blade.php, resources/views/livewire/entries/payment/upsert.blade.php, resources/views/livewire/entries/receipt/index.blade.php, resources/views/livewire/entries/receipt/upsert.blade.php, resources/views/livewire/entries/sales/upsert.blade.php, tests/Feature/Livewire/Common/BankListTest.php, tests/Feature/Livewire/Common/ReceipttypeListTest.php
=> #70 bank and receipttype

aaran/Common/Tests/CityTest.php
=> #71 Unit test(city)

app/Livewire/Common/CityList.php, app/Livewire/Entries/Purchase/Upsert.php, app/Livewire/Entries/Sales/Upsert.php, app/Livewire/Trait/CommonTrait.php, resources/views/livewire/common/city-list.blade.php, resources/views/livewire/entries/purchase/upsert.blade.php, resources/views/livewire/entries/sales/upsert.blade.php, resources/views/vendor/livewire/simple-tailwind.blade.php, resources/views/vendor/livewire/tailwind.blade.php, resources/views/vendor/pagination/bootstrap-4.blade.php, resources/views/vendor/pagination/bootstrap-5.blade.php, resources/views/vendor/pagination/default.blade.php, resources/views/vendor/pagination/semantic-ui.blade.php, resources/views/vendor/pagination/simple-bootstrap-4.blade.php, resources/views/vendor/pagination/simple-bootstrap-5.blade.php, resources/views/vendor/pagination/simple-default.blade.php, resources/views/vendor/pagination/simple-tailwind.blade.php, resources/views/vendor/pagination/tailwind.blade.php
=> #72 field validation
